services:
  - docker

install:
  - docker pull chef/chefdk

branches:
  only:
    - master

script:
  - docker run -t chef/chefdk chef -v
  - docker run -v $PWD:/cookbook -w /cookbook -t chef/chefdk delivery local all
